/*    ==Parâmetros de Script==

    Versão do Servidor de Origem : SQL Server 2017 (14.0.3015)
    Edição do Mecanismo de Banco de Dados de Origem : Microsoft SQL Server Enterprise Edition
    Tipo do Mecanismo de Banco de Dados de Origem : SQL Server Autônomo

    Versão do Servidor de Destino : SQL Server 2017
    Edição de Mecanismo de Banco de Dados de Destino : Microsoft SQL Server Enterprise Edition
    Tipo de Mecanismo de Banco de Dados de Destino : SQL Server Autônomo
*/

USE [master]
GO

/****** Object:  Database [BigBang]    Script Date: 27/02/2018 22:50:32 ******/
DROP DATABASE [BigBang]
GO

/****** Object:  Database [BigBang]    Script Date: 27/02/2018 22:50:32 ******/
CREATE DATABASE [BigBang]
GO

ALTER DATABASE [BigBang] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BigBang].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BigBang] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BigBang] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BigBang] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BigBang] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BigBang] SET ARITHABORT OFF 
GO

ALTER DATABASE [BigBang] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BigBang] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BigBang] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BigBang] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BigBang] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BigBang] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BigBang] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BigBang] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BigBang] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BigBang] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BigBang] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BigBang] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BigBang] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BigBang] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BigBang] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BigBang] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [BigBang] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BigBang] SET RECOVERY FULL 
GO

ALTER DATABASE [BigBang] SET  MULTI_USER 
GO

ALTER DATABASE [BigBang] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BigBang] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BigBang] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BigBang] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BigBang] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BigBang] SET QUERY_STORE = OFF
GO

USE [BigBang]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [BigBang] SET  READ_WRITE 
GO

