version: '3'
services: 
    bigbang:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5151:5151"
        networks: 
            - nginx-proxy
        restart: always
        depends_on:
            - sql_dev
        environment:
            VIRTUAL_HOST: 'bigbang.lennonalves.com.br,bigbang.lennonalves.com'
            VIRTUAL_PORT: 5151
    sql_dev:
        image: microsoft/mssql-server-linux:2017-latest
        ports:
            - "1401:1433"
        networks: 
            - nginx-proxy
        restart: unless-stopped
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Developer@2018
            - MSSQL_PID=Developer
networks:
  nginx-proxy:
    external: true
